#!/bin/bash

function calculateMakespan {
	queued_lastupdate_file="/tmp/min_queued_lastupdate.txt"
	finished_lastupdate_file="/tmp/max_finished_lastupdate.txt"
	MIN_QUEUED_LASTUPDATE=`cat "$queued_lastupdate_file"`
	MAX_FINISHED_LASTUPDATE=`cat "$finished_lastupdate_file"`
	expr $MAX_FINISHED_LASTUPDATE - $MIN_QUEUED_LASTUPDATE
}

function getImagesStatus {

	#Geting info about db
	ip=$scheduler_ip
	port=$scheduler_db_port
	db_name=$sebal_db_name
	db_username=$sebal_db_user
	db_password=$sebal_db_password

	# Setting password to access db
	file="$HOME/.pgpass"
	if [ -f "$file" ]
	then
	    ## echo "File $file already exists. Replacing deleting now."
	    rm -f $file
	fi

	#Writing password in .pgpass and changing permissions
	echo "$ip:$port:$db_name:$db_username:$db_password" >> $file
	chmod 0600 "$HOME/.pgpass"

	# Counting images in each state in NASA_IMAGES table
	downloaded=`psql -h $ip -U $db_username -c "COPY (SELECT COUNT(*) FROM nasa_images WHERE state = 'downloaded') TO STDOUT" $db_name`
	running=`psql -h $ip -U $db_username -c "COPY (SELECT COUNT(*) FROM nasa_images WHERE state = 'running') TO STDOUT" $db_name`
	finished=`psql -h $ip -U $db_username -c "COPY (SELECT COUNT(*) FROM nasa_images WHERE state = 'finished') TO STDOUT" $db_name`
	queued=`psql -h $ip -U $db_username -c "COPY (SELECT COUNT(*) FROM nasa_images WHERE state = 'queued') TO STDOUT" $db_name`
	all_images=`psql -h $ip -U $db_username -c "COPY (SELECT COUNT(*) FROM nasa_images) TO STDOUT" $db_name`

	if [[ $all_images == $queued ]]; then
		queued_lastupdate_file="/tmp/min_queued_lastupdate.txt"
		rm "$queued_lastupdate_file" 2> /dev/null
		MIN_QUEUED_LASTUPDATE=`psql -h $ip -U $db_username -c "COPY (SELECT MIN(utime) FROM nasa_images WHERE state = 'queued') TO STDOUT" $db_name`
		date --date="$MIN_QUEUED_LASTUPDATE" +"%s" > "$queued_lastupdate_file"
	fi

	#Condition to give status of the images
	if [[ $all_images == 0 || $all_images == $downloaded ]]
	then
	    echo "Idle"  
	elif [[ $running > 0 || $queued > 0 ]]
	then
	    echo "Running" 
	elif [[ $all_images == $finished ]]
	then
	    echo "Done"
	    finished_lastupdate_file="/tmp/max_finished_lastupdate.txt"
		rm "$finished_lastupdate_file" 2> /dev/null
		MAX_FINISHED_LASTUPDATE=`psql -h $ip -U $db_username -c "COPY (SELECT MAX(utime) FROM nasa_images WHERE state = 'finished') TO STDOUT" $db_name` 
		date --date="$MAX_FINISHED_LASTUPDATE" +"%s" > "$finished_lastupdate_file"
	else
	    echo "ERROR: Not possible to provide the state of the images"
	fi
}
